version: 1.0.{build}
image: Visual Studio 2015
platform:
- Win32
- x64
- ARM64
configuration:
- Release

for:
-
  matrix:
    only:
      - platform: ARM64
        image: Visual Studio 2019

before_build:
- ps: >-
    If ($env:APPVEYOR_BUILD_VERSION -Like "1.0*") {
      $version = Source/Script/SetGitProperties.cmd
      appveyor UpdateBuild -Version $version
    }
    If ($env:PLATFORM -eq 'ARM64') {
      Write-Host 'Building for ARM64. Using Win32 UpdateVersion.'
      MSBuild.exe /p:Platform=Win32 /p:Configuration=$env:CONFIGURATION $env:APPVEYOR_BUILD_FOLDER\Source\UpdateVersion
    }
build:
  project: Project64.sln
  parallel: true
  verbosity: minimal
after_build:
- Source/Script/package_zip.cmd %APPVEYOR_BUILD_VERSION%-%platform%.zip %platform%

artifacts:
- path: Package/*.zip
