version: 1.0.{build}
platform:
- Win32
- x64
- ARM64
configuration:
- Release

environment:
  matrix:
    - PLATFORM: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PLATFORM: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PLATFORM: ARM64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

before_build:
- ps: >-
    If ($env:APPVEYOR_BUILD_VERSION -Like "1.0*") {
      $version = Source/Script/SetGitProperties.cmd
      appveyor UpdateBuild -Version $version
    }
    If ($env:PLATFORM -eq 'ARM64') {
      Write-Host 'Building for ARM64. Using Win32 UpdateVersion.'
      MSBuild.exe /p:Platform=Win32 Source\UpdateVersion
    }
build:
  project: Project64.sln
  parallel: true
  verbosity: minimal
after_build:
- Source/Script/package_zip.cmd %APPVEYOR_BUILD_VERSION%-%platform%.zip %platform%

artifacts:
- path: Package/*.zip
